### ISSUE TITLE
Issue with Scroll bar

### ISSUE THREAD

**Issue by SidduLakkarse** [isaacplmann/ngx-contextmenu#125]
Hi Isaac Mann,

How do i add scroll bar for context menu. i am  tried to use cdkScrollable ,but it is not working.

Could you please help me out this issue.

Attached the screen shot for your reference.
![scrollissue](https://user-images.githubusercontent.com/36532513/41721147-c930cbee-7582-11e8-957f-909ddbd421c8.png)

**Comment by isaacplmann** [comment]
Try something like this:

```css
.ngx-contextmenu > ul {
  overflow: auto;
  max-height: 200px;
}
```
