### ISSUE TITLE
On dialog context menu no working fine

### ISSUE THREAD

**Issue by MuslimMunir** [isaacplmann/ngx-contextmenu#46]
On dialog context menu is not working fine its is coming under the dialog
I am using material and angular4 latest

**Comment by isaacplmann** [comment]
Sounds like you need to give the context menu a z-index in your css.

Something like this:

```css
.ngx-contextmenu .dropdown-menu {
  z-index: 1000,
}
```

You can choose whatever high number works for your z-index.
